# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Calcul_project\Calcul_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(635, 1000)
        Form.setMinimumSize(QtCore.QSize(635, 1000))
        Form.setMaximumSize(QtCore.QSize(635, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\Calcul_project\\../calculator-01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background: #111518,")
        self.text_calllcullator = QtWidgets.QLabel(Form)
        self.text_calllcullator.setGeometry(QtCore.QRect(240, 10, 151, 31))
        self.text_calllcullator.setStyleSheet("QLabel{\n"
"    color:#FFFFFF,\n"
"    background-color: #111518,\n"
"    font: 75 13pt \"MicroExtendFLF\",\n"
"}")
        self.text_calllcullator.setTextFormat(QtCore.Qt.AutoText)
        self.text_calllcullator.setWordWrap(False)
        self.text_calllcullator.setObjectName("text_calllcullator")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(50, 89, 531, 151))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border-style: outset,\n"
"    background-color: #212327,\n"
"    color: white,\n"
"    font: 75 80pt \"MicroExtendFLF\",\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 329, 531, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_split = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_split.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 40pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 25pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_split.setObjectName("pushButton_split")
        self.gridLayout.addWidget(self.pushButton_split, 0, 3, 1, 1)
        self.pushButton_procent = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_procent.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 30pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 20pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_procent.setObjectName("pushButton_procent")
        self.gridLayout.addWidget(self.pushButton_procent, 0, 2, 1, 1)
        self.pushButton_del = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_del.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 30pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 20pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_del.setObjectName("pushButton_del")
        self.gridLayout.addWidget(self.pushButton_del, 0, 1, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_plus.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 40pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 25pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.gridLayout.addWidget(self.pushButton_plus, 3, 3, 1, 1)
        self.pushButton_min = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 40pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 25pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_min.setObjectName("pushButton_min")
        self.gridLayout.addWidget(self.pushButton_min, 2, 3, 1, 1)
        self.pushButton_multiplication = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_multiplication.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 40pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 25pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_multiplication.setObjectName("pushButton_multiplication")
        self.gridLayout.addWidget(self.pushButton_multiplication, 1, 3, 1, 1)
        self.pushButton_clean = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_clean.setStyleSheet("QPushButton{\n"
"    border: 2px solid #3DCC79,\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #111518,\n"
"    color: #3DCC79,\n"
"    font: 75 45pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #111518, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 35pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.gridLayout.addWidget(self.pushButton_clean, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 3, 2, 1, 1)
        self.pushButton_factorial = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_factorial.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 40pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 25pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_factorial.setObjectName("pushButton_factorial")
        self.gridLayout.addWidget(self.pushButton_factorial, 4, 0, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_0.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: white,\n"
"    font: 75 38pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 28pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 4, 1, 1, 1)
        self.pushButton_tochka = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_tochka.setStyleSheet("QPushButton{\n"
"    border-radius: 50px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #303236,\n"
"    color: #3DCC79,\n"
"    font: 75 40pt \"MicroExtendFLF\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: white,\n"
"    font: 75 25pt \"MicroExtendFLF\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #3DCC79\n"
"        ),\n"
"    }")
        self.pushButton_tochka.setObjectName("pushButton_tochka")
        self.gridLayout.addWidget(self.pushButton_tochka, 4, 2, 1, 1)
        self.pushButton_end_data = QtWidgets.QPushButton(Form)
        self.pushButton_end_data.setGeometry(QtCore.QRect(450, 850, 131, 231))
        self.pushButton_end_data.setStyleSheet("QPushButton{\n"
"    border-radius: 65px,\n"
"    width: 103px,\n"
"    height: 103 px,\n"
"    background-color: #3DCC79,\n"
"    color: #111518,\n"
"    font: 75 60pt \"Cambria Math\",\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #3DCC79, stop: 1 #19994C\n"
"        ),\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset,\n"
"    color: #3DCC79,\n"
"    font: 75 50pt \"Cambria Math\",\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #303236, stop: 1 #212327\n"
"        ),\n"
"    }")
        self.pushButton_end_data.setObjectName("pushButton_end_data")
        self.text_INPUT = QtWidgets.QLabel(Form)
        self.text_INPUT.setGeometry(QtCore.QRect(50, 70, 71, 31))
        self.text_INPUT.setStyleSheet("QLabel{\n"
"    color:#595959,\n"
"    font: 75 13pt \"MicroExtendFLF\",\n"
"    background-color: #212327,\n"
"}")
        self.text_INPUT.setTextFormat(QtCore.Qt.AutoText)
        self.text_INPUT.setWordWrap(False)
        self.text_INPUT.setObjectName("text_INPUT")
        self.text_DATA = QtWidgets.QLabel(Form)
        self.text_DATA.setGeometry(QtCore.QRect(120, 70, 61, 30))
        self.text_DATA.setStyleSheet("QLabel{\n"
"    color:#B3B3B3,\n"
"    font: 75 13pt \"MicroExtendFLF\",\n"
"    background-color: #212327,\n"
"}")
        self.text_DATA.setTextFormat(QtCore.Qt.AutoText)
        self.text_DATA.setWordWrap(False)
        self.text_DATA.setObjectName("text_DATA")
        self.graphicsView_1 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_1.setGeometry(QtCore.QRect(0, -40, 641, 91))
        self.graphicsView_1.setStyleSheet("QGraphicsView{\n"
"    border-radius: 35px,\n"
"    border-style: outset,\n"
"    background-color: #111518,\n"
"}")
        self.graphicsView_1.setObjectName("graphicsView_1")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 270, 641, 90))
        self.graphicsView_2.setStyleSheet("QGraphicsView{\n"
"    border-radius: 35px,\n"
"    border-style: outset,\n"
"    background-color: #3DCC79,\n"
"}")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_3.setGeometry(QtCore.QRect(40, 20, 16, 16))
        self.graphicsView_3.setStyleSheet("QGraphicsView{\n"
"    border-radius: 7px,\n"
"    border-style: outset,\n"
"    background-color: #3DCC79,\n"
"}")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_4.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.graphicsView_4.setStyleSheet("QGraphicsView{\n"
"    border-radius: 7px,\n"
"    border-style: outset,\n"
"    background-color: #3DCC79,\n"
"}")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_5.setGeometry(QtCore.QRect(100, 20, 16, 16))
        self.graphicsView_5.setStyleSheet("QGraphicsView{\n"
"    border-radius: 7px,\n"
"    border-style: outset,\n"
"    background-color: #3DCC79,\n"
"}")
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_6.setGeometry(QtCore.QRect(0, 300, 641, 90))
        self.graphicsView_6.setStyleSheet("QGraphicsView{\n"
"    border-radius: 35px,\n"
"    border-style: outset,\n"
"    background-color: #111518,\n"
"}")
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(Form)
        self.graphicsView_7.setGeometry(QtCore.QRect(0, -10, 641, 341))
        self.graphicsView_7.setStyleSheet("QGraphicsView{\n"
"    border-style: outset,\n"
"    background-color: #212327,\n"
"}")
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_7.raise_()
        self.graphicsView_2.raise_()
        self.graphicsView_6.raise_()
        self.graphicsView_1.raise_()
        self.text_calllcullator.raise_()
        self.lineEdit.raise_()
        self.gridLayoutWidget.raise_()
        self.pushButton_end_data.raise_()
        self.text_INPUT.raise_()
        self.text_DATA.raise_()
        self.graphicsView_3.raise_()
        self.graphicsView_4.raise_()
        self.graphicsView_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculator"))
        self.text_calllcullator.setText(_translate("Form", "CAIIICUIIIATOR"))
        self.pushButton_split.setText(_translate("Form", "/"))
        self.pushButton_procent.setText(_translate("Form", "%"))
        self.pushButton_del.setText(_translate("Form", "DEL"))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_min.setText(_translate("Form", "-"))
        self.pushButton_multiplication.setText(_translate("Form", "x"))
        self.pushButton_clean.setText(_translate("Form", "←"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_factorial.setText(_translate("Form", "!"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_tochka.setText(_translate("Form", "."))
        self.pushButton_end_data.setText(_translate("Form", "="))
        self.text_INPUT.setText(_translate("Form", "INPUT"))
        self.text_DATA.setText(_translate("Form", "DATA"))


